### ISSUE TITLE
Absolute paths in output

### ISSUE THREAD

**Issue by kurai021** [alanshaw/markdown-pdf#100]
How can I generate the pdf in a folder located in $HOME or %UserProfile% ?, I only can in the project folder.

**Comment by alanshaw** [comment]
Did you try the `-o` option? https://github.com/alanshaw/markdown-pdf#usage

**Comment by kurai021** [comment]
but how to do it in JS?

**Comment by alanshaw** [comment]
https://github.com/alanshaw/markdown-pdf#topathpath-cb--topath-cb
https://github.com/alanshaw/markdown-pdf#from-string-to-path
https://github.com/alanshaw/markdown-pdf#from-multiple-paths-to-multiple-paths

**Comment by kurai021** [comment]
I have read the documentation, but instead of copy the pdf in the path in my home folder, it creates a folder called $HOME in the project folder

**Comment by anko** [comment]
@kurai021 Could you show what exactly you're doing?

Perhaps you passed a string `"$HOME"` as the output path, instead of `process.env.HOME`? Markdown-pdf doesn't automatically expand shell variables in file names.

**Comment by kurai021** [comment]
hey thanks, it maybe give some clue
