### ISSUE TITLE
How to generate TOC in generated PDF using markdown-toc?

### ISSUE THREAD

**Issue by rkrejcii** [alanshaw/markdown-pdf#103]
Hi.

I will be grateful for any hint how to use [markdown-toc](https://github.com/jonschlinkert/markdown-toc) with markdown-pdf for dynamic table of content insertion using [`toc.insert()`](https://github.com/jonschlinkert/markdown-toc#tocinsert) method.

The problem is that as far as I understand the logic, `preProcessMd` works with streams, but `toc.insert` needs to process full Markdown file first (to generate TOC and insert it in Markdown file on position defined by `<!-- toc -->` tag).

After few unsuccessful attempts I have even doubts if this is doable.

Thanks.

**Comment by anko** [comment]
You can process the Markdown file with markdown-toc in a shell script before handing it to markdown-pdf:

```
cp input.markdown input-with-toc.markdown
markdown-toc -i input-with-toc.markdown
markdown-pdf input-with-toc.markdown
```

Alternatively, you could use [concat-stream](https://github.com/maxogden/concat-stream) to collect the entire `preProcessMd` stream, transform that with markdown-toc, and output the result as stream data.

Let me know if you need further implementation hints.

**Comment by PradyumnaR** [comment]
@anko I need some help for generating TOC with page numbers can I do it with markdown-toc by giving at remarkable plugin ?
Any help would be appreciated.
thank you

**Comment by anko** [comment]
> generating TOC with page numbers

To my knowledge, there is no web API that tells you what printed page an element appears on. Until that exists, a table of contents with page numbers isn't possible to do automatically.

**Comment by PradyumnaR** [comment]
@anko thanks for getting back. Can I use markdown-toc for generating toc while my markdown is getting converted to pdf?
```
markdown({remarkable: {plugins: [require('markdown-toc')]}}).from().to()
```

**Comment by anko** [comment]
That's covered in [markdown-toc's readme § toc.plugin](https://github.com/jonschlinkert/markdown-toc#tocplugin).
