### ISSUE TITLE
images?!

### ISSUE THREAD

**Issue by thkang2** [alanshaw/markdown-pdf#11]
it seems images aren't included in the resulting PDF file.

I put some images into my MD document, using inline span syntax (http://daringfireball.net/projects/markdown/syntax#img)

```
![Alt text](/path/to/img.jpg)
```

the resulting image shows in html file, which is an intermediate in your code

```
function markdownToPdfTask (filePath, opts) {
    ....
    var html = marked(data) // I checked temporal html contains valid <IMG> tags converted from above markdown
```

however, they're just blank in the resulting PDF.

```
markdown-pdf test.md # test.pdf has no images
```

if I save the intermediate html and load it in chrome, they render correctly.

is there any solution for this? markdown-pdf produces very beautiful pdf files, and I really want to use them in my report generation.

**Comment by pseudosavant** [comment]
My solution to this issue was to load all the markdown files myself into a large string and prepend `file:///` and `process.cwd()`. I also convert spaces to %20 and convert backslashes (from Windows) to forward slashes.

Example:

    const absolutePath = 'file:///' + process.cwd().replace(/ /g, '%20').replace(/\\/g, '/') + '/';
    const find = /img src="/g;
    const replace = 'img src="' + absolutePath;
    const mdStr = mdSourceStr.replace(find, replace);

**Comment by abrahamf24** [comment]
> 
> 
> @strk, here's a solution I've hacked together using [Cheerio](https://github.com/cheeriojs/cheerio):
> 
> ```js
> var markdownpdf = require("markdown-pdf")
>   , split = require("split")
>   , through = require("through")
>   , duplexer = require("duplexer")
> var through = require('through');
> var cheerio = require('cheerio');
> 
> // This should be where your .md file lives
> var imgBasePath = __dirname + "/markdown/";
> var preProcessHtml = function() {
> 
>     return through(function(data) {
>         var $ = cheerio.load(data);
> 
>         $('img[src]').each(function(i, elem) {
>             var path = $(this).attr('src');
>             path = imgBasePath + path;
>             $(this).attr('src', path);
>         });
> 
>         this.queue($.html());
>     });
> };
> 
> markdownpdf({preProcessHtml: preProcessHtml})
>   .from("/path/to/document.md")
>   .to("/path/to/document.pdf", function () { console.log("Done") })
> ```
> 
> It's certainly not a cure-all - I'd like to see this in markdown-pdf natively - but it might get you out of a bind.

I added 

`pathSrc = 'file:///'+imgBasePath + path`
