### ISSUE TITLE
Docs: it's hard to understrand how to use preProcessMd

### ISSUE THREAD

**Issue by evil-shrike** [alanshaw/markdown-pdf#110]
The README says that `preProcessMd` callback returns: 

> A function that returns a through2 stream that transforms the markdown before it is converted to HTML.

but in example "Transform markdown before conversion" another module `through` is used. 

So it's unclear how to pre-process markdown files. 

For example I need to cut off a header in every file with YAML like this:

```

---
title: Overview
area: Docs

---
```

How it could be done in `preProcessMd` ?

I tried an approach from the example with split+through+duplexer - I can't understand where a file start and where it ends. 
With through2 I tried to accumulate text in transform callback and process it in flush callback. But executing a regex again multiline text is hard:
(this doesn't work)

```
  var content = '';
  return through(
    function transform (chunk, enc, cb) {
      content += chunk;
      cb();
    },
    function flush (cb) {
      if (content) {
        var res = content.replace(/---\s*[.\s]*---/gmi, '');
        this.push(res);
      }
      content = '';
      cb();
    });
```

It'd be much better to process a input line by line. But despite of the "split+through+duplexer" example I need to known where a file starts (to begin searching for the first "---") and where it ends (to reset the process). When I find the second "---" I can cut it off.

**Comment by alanshaw** [comment]
Did you get this working? It would be good if you could send a PR to update the example that's using "through" not "through2".

It might be useful for others if you also send a PR to add this as an example as it's probably a reasonably common use case!

**Comment by evil-shrike** [comment]
> Did you get this working?

No, I gave up.

**Comment by antenando** [comment]
I got it working with `through2`:

```js
function preProcessMd () {
  return through2((data, enc, cb) => {
    cb(null, new Buffer(data.toString().replace(/^---\n.*?---\n/s, '')));
  });
}
```

**Comment by antenando** [comment]
And if you want to perform several replaces...
```js
function preProcessMd() {
  return through2((data, enc, cb) => {
    let nd = data.toString()
      .replace(/^---\n.*?---\n/s, '')
      .replace(/Fernando/, 'whatever');

    cb(null, new Buffer(nd));
  });
}
```
