### ISSUE TITLE
There are no border output in pdf file

### ISSUE THREAD

**Issue by Moxmi** [alanshaw/markdown-pdf#111]
When i try to transform a md file to a pdf file, i found the table border has not display.

**Comment by GAumala** [comment]
I have this issue as well. This is how the table is rendered:

![screenshot from 2016-12-10 22-40-25](https://cloud.githubusercontent.com/assets/5729175/21077935/bb1ae3b6-bf29-11e6-8655-7dc46027fa92.png)

I generated this file from the command line, using no arguments. Maybe it is an issue with the `remarkable` module?

**Comment by Moxmi** [comment]
@GAumala I resolved this issue, in fact the table has border but it color is same to background...
So here you should modify 'node_modules/marksnap/node_modules/markdown-pdf/css/pdf.css' to change the css style of table.

**Comment by alanshaw** [comment]
This is likely the default styling of [HTML5 Boilerplate](https://html5boilerplate.com/). You can pass your own stylesheet using the [`cssPath` option](https://github.com/alanshaw/markdown-pdf#optionscsspath)
