### ISSUE TITLE
Calling an asynchronous function without callback **depricated** - fs.close()

### ISSUE THREAD

**Issue by SavageWilliam** [alanshaw/markdown-pdf#114]
Getting the error 
```
 DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

Using ```node --trace-warnings yourscript.js``` it looks like the error is coming from index.js line:91 and line:96 with the fs.close method. 

Possible fix to use [fs.closeSync()](https://nodejs.org/api/fs.html#fs_fs_closesync_fd) ? 

![image](https://cloud.githubusercontent.com/assets/15717822/22974858/3a204d46-f37c-11e6-8d07-3af8016a9650.png)

@alanshaw

**Comment by alanshaw** [comment]
I think just give the `fs.close` calls a callback what logs a warning if an error occurred. I'd welcome a PR.

**Comment by SavageWilliam** [comment]
@alanshaw Sure sounds good. I'm happy to do that 👍
