### ISSUE TITLE
no border for table in Markdown

### ISSUE THREAD

**Issue by wbo4958** [alanshaw/markdown-pdf#117]
Hi, 

```
# cat example.md
aa|bb|cc
--|--|--
ee|ff|gg 

# markdown-pdf example.md
```
The rendered table has no borders.

![image](https://cloud.githubusercontent.com/assets/1320706/26051042/8b2e6260-3993-11e7-9439-9305c83b8072.png)

**Comment by anko** [comment]
The default CSS has no borders. You can change it with [`--css-path`](https://github.com/alanshaw/markdown-pdf#usage) though:

```
$ cat example.md
aa|bb|cc
--|--|--
ee|ff|gg
$ cat custom.css
td, th {
    border: 1px solid grey
}
$ markdown-pdf --css-path='custom.css' example.md
```
![shot](https://cloud.githubusercontent.com/assets/5231746/26122742/7057c62e-3a70-11e7-812a-f783d6f7a9d3.png)

**Comment by wbo4958** [comment]
Thx very much. worked.
