### ISSUE TITLE
can I preload external image into pdf ? 

### ISSUE THREAD

**Issue by a-eid** [alanshaw/markdown-pdf#124]
markdown docs have a lot of external `imgur` images , I am wonder if it is possible to load them before converting to `pdf`

**Comment by anko** [comment]
You could download them to your local computer, then include them with

    ![image](/path/to/local/image.png)

in the Markdown, as with any other image you have stored locally.

**Comment by a-eid** [comment]
does the **library** offer away to automate this task before converting to `pdf`

**Comment by anko** [comment]
> does the library offer away to automate this task

No. It just converts Markdown files to PDFs. For other purposes, there are better tools.

How I'd go about automating that, if you find yourself doing it often: Create a [remark](https://github.com/wooorm/remark) plugin that looks for [`Image` nodes](https://github.com/syntax-tree/mdast#image), downloads the remote ones to the local machine, and replaces the nodes' `url` attributes with paths to the local files.

**Comment by anko** [comment]
Closing, because I think this is out of scope for adding to markdown-pdf.
