### ISSUE TITLE
syntax highlighting in markdown are not properly converted in the output pdf

### ISSUE THREAD

**Issue by PradyumnaR** [alanshaw/markdown-pdf#125]

**Comment by PradyumnaR** [comment]
for example 
```
text
```

when we see the output in pdf it is giving me text surrounded by rectangle
Thanks

**Comment by anko** [comment]
Text surrounded by a rectangle sounds like what I'd expect code blocks to look like in a PDF. If the style is not to your liking, you can [change the CSS](https://github.com/alanshaw/markdown-pdf#optionscsspath).

### Example

With these files

`test.markdown`:
```markdown
    text
```

`custom.css`:
```css
pre { border: none }
```

I ran this command

    markdown-pdf --css-path=custom.css test.markdown

and got output text with no border.

**Comment by PradyumnaR** [comment]
Cool thanks, Anko. It worked for me.
