### ISSUE TITLE
resolution different on headless server vs local machine

### ISSUE THREAD

**Issue by awb99** [alanshaw/markdown-pdf#128]
I created some html code that I then render on both my development machine, and 
also on a headless server. I do notice two behaviors:

1. The server renders font in a really bad resolution. The dev machine resolution is perfect.

2. When I open the same html file on google chrome or on firefox, and I print it to PDF from this
browsers, then all the layouting is fine. But the rendering via this library seems to be much bigger
than on the web browser. I have layouted the html to fit beautifully on a A4 page. And via webbrowser
it works fine; but via this library it does not.

Any ideas?

Thanks
Andreas

**Comment by anko** [comment]
I'll focus on the first problem for now.

Initial guess: OS-dependent PhantomJS issue.

Questions:

 - What options are you running markdown-pdf with? Any custom `--phantom-path`?
 - What operating system is each running?
