### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by ab-smith** [alanshaw/markdown-pdf#129]
Hello,
  Whenever called, I get this warning : 
(node:5693) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 2 end listeners added. Use emitter.setMaxListeners() to increase limit
markdown-pdf --version = 8.0.0 on Mac OS 
  There's no problem with the build though.
Thank you,

**Comment by alanshaw** [comment]
Dupe of #98
