### ISSUE TITLE
Empty pdf

### ISSUE THREAD

**Issue by umaknow-alexandre** [alanshaw/markdown-pdf#135]
### Hi there, 

I'm trying to use markdown-pdf but I must be missing something because I just can't get anything more than an empty pdf.

I've added a gulp task within my project that only does de following: 
```
const mdpdf = require('markdown-pdf');
mdpdf().from.string("###Test\n\nSomething").to('./test.pdf', function () {
    gutil.log("Created");
  });
```

When I run the task, the pdf is successfully created, but it's empty and I can't open it.  I'm not having any error log or anything, just nothing at all. 

I'v try that on both my Mac and my PC running windows 10 and the result is the same.

I tried using the command line and weirdly enough it's working! I must be missing something here...

Any help would be appreciated since I couldn't fin any other .md -> .pdf converter for gulp!

**Comment by alanshaw** [comment]
That's weird, could you check if there's an error passed to the callback?

**Comment by umaknow-alexandre** [comment]
The callback is actually never called and when using gulp, I'm not getting any error at all, which is super weird...

**Comment by alanshaw** [comment]
I can't recreate

<img width="640" alt="screen shot 2017-12-15 at 15 14 28" src="https://user-images.githubusercontent.com/152863/34048209-c5f030ee-e1aa-11e7-85ca-a416b1da9b8e.png">

**Comment by umaknow-alexandre** [comment]
I know it's working this way. I can get it to work too.
<img width="812" alt="screen shot 2017-12-15 at 10 22 59 am" src="https://user-images.githubusercontent.com/30940503/34048536-15d09622-e182-11e7-99f9-7d4f4e2b26d3.png">

I was just letting you know that inside a gulp task, it's not working. I don't know if it's something with gulp, but it's the first package to do that so I'll figure out a way around, but you happen to know what's up with gulp it'd be appreciated.

**Comment by alanshaw** [comment]
I don't see any gulp code here? Are you using `gulp-markdown-pdf`? I'm not sure how I can help.

**Comment by umaknow-alexandre** [comment]
I did try with gulp-markdown-pdf and with only markdown-pdf without luck. I ended up using gulp-run to run an external script that does exactly what's in my last screenshot. It's a bit hacky but it works so it's gonna stay like that for now! 
Thanks!
![screen shot 2017-12-15 at 12 06 04 pm](https://user-images.githubusercontent.com/30940503/34052437-5aea5dca-e190-11e7-9971-d718ee1243ac.png)
