### ISSUE TITLE
markdown-pdf take LF & CR/LF

### ISSUE THREAD

**Issue by neooblaster** [alanshaw/markdown-pdf#150]
Hi Markdown-pdf team,

I saw that `Markdown-pdf` strictly respects new line char (LF & CR/LF).

In **JetBrain editor** (PhpStorm), you can automatically made cariage return when current line is too long.
In markdown, a new line is made when you make two cariages return : 

````markdown
Paragraph 1 (start)
New line in Markdown, no cariage return for rendered text (follow previous line)
````

**Result in PhpStorm:** 
![image](https://user-images.githubusercontent.com/22078558/46480966-91630980-c7f2-11e8-8d9c-cf1254efb513.png)

**Result in PDF Document :** 
![image](https://user-images.githubusercontent.com/22078558/46481055-c40d0200-c7f2-11e8-8d7b-b5c9b15ca0f9.png)

````markdown
Paragraph 1

Paragraph 2
````

**Normal result in PhpStorm & PDF Document**
![image](https://user-images.githubusercontent.com/22078558/46480980-9cb63500-c7f2-11e8-8ff0-97793ca16772.png)

Is it an issue or a default setting behavior which can be modified ?

Thank you for your support, because your solution is very usefull for me.
I was looking for a tool to render my MD File easly since a very long time.

Best Regards,
Nicolas DUPRE

**Comment by trombik** [comment]
had the same issue, #123 works for me

**Comment by neooblaster** [comment]
Hi Trombik,

Thank you for your reply. I update my alias to use option `-m '{"breaks": false}'` and that work perfectly.
I close the issue because that can be considers as normal behavior and setting adjustements.

It's not necessary to have to many issues on that subject.

Best regards
Nicolas DUPRE..
