### ISSUE TITLE
Issues with installing

### ISSUE THREAD

**Issue by Edward70891** [alanshaw/markdown-pdf#151]
I just get the following when I try to install it

```
[edward in ~] $: sudo npm install -g markdown-pdf
/usr/bin/markdown-pdf -> /usr/lib/node_modules/markdown-pdf/bin/markdown-pdf

> phantomjs-prebuilt@2.1.16 install /usr/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /usr/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1541017488065/phantomjs-2.1.1-linux-x86_64 -> /usr/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /usr/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-31T20_24_50_220Z-debug.log
g /usr/lib/node_modules/markdown-pdf/node_modules/phantomjs-prebuilt/lib/phantom
```
[2018-10-31T20_27_56_571Z-debug.log](https://github.com/alanshaw/markdown-pdf/files/2536298/2018-10-31T20_27_56_571Z-debug.log)

**Comment by nukeop** [comment]
Getting the same error here

**Comment by neooblaster** [comment]
Hi @Edward70891, @nukeop 
 
Did you try again to install markdown-pdf after cleaning files ? I have already get similar error. 
I completly clean files for the Node application that I'm trying to install (here markdown-pdf)

Delete Markdown-pdf Files : 

* File : `%APPDATA%\npm\markdown-pdf`
* File : `%APPDATA%\npm\markdown-pdf.cmd`
* Folder `%APPDATA%\npm\node_modules\markdown-pdf\`.

Maybe an issue was occurs during installation producing your error.

Best Regards,
Nicolas DUPRE.

**Comment by Edward70891** [comment]
I'm on Linux, so I don't know how many of these installation files are the
same, but I tried removing all the ones I could find, and nothing changed

**Comment by neooblaster** [comment]
Hi @Edward70891,

Can you try with this following thread.
I think the right path is `/usr/local/lib/node_modules`.

Nicolas

**Comment by shwinshaker** [comment]
`npm install -g  markdown-pdf --ignore-scripts` seems to temporarily solve the problem.

**Comment by Edward70891** [comment]
This worked perfectly, thanks.

**Comment by JorgeDLG** [comment]
> `npm install -g markdown-pdf --ignore-scripts` seems to temporarily solve the problem.

Same problem and this don't work for me
