### ISSUE TITLE
Question: Code blocks?

### ISSUE THREAD

**Issue by origal** [alanshaw/markdown-pdf#36]
Hey. I want to turn a README.md of a project of mine into a PDF.

This file contains code blocks. I see that no matter if I use ` or code tags, these code blocks are just shown as regular text, as if those tags are just ignored.

I have managed to accomplish this with the CLI like so:

`markdown-pdf -s code.css README.pdf`

code.css only includes this one-liner with the gitlab markdown, which I thought is a little nicer then the git standard markdown:

`code{padding:2px 4px;font-size:90%;color:#c7254e;background-color:#f9f2f4;white-space:nowrap;border-radius:4px}`

Should we maybe make this standard? I don't know. I guess at least some of us developers are using this for code related stuff.

All the best.

**Comment by JobaDiniz** [comment]
+1

**Comment by jasonb-vbt** [comment]
+1, but it would be especially nice if markdown-pdf supported intented code blocks as well as ``` delimited code blocks. For me, it's treating indented code blocks as ordinary paragraphs, which sucks as changing block styles would mean going back and editing a *lot* of md files...

**Comment by alanshaw** [comment]
Closing as this is pretty old now. markdown-pdf uses highlight.js and allows you to customise the styles through [cssPath](https://github.com/alanshaw/markdown-pdf#optionscsspath) and [highlightCssPath](https://github.com/alanshaw/markdown-pdf#optionshighlightcsspath)
