### ISSUE TITLE
Huge file size

### ISSUE THREAD

**Issue by dandaka** [alanshaw/markdown-pdf#37]
I have created simple PDF out of 33 KB .md → 9 MB size... For 8 pages document without pictures it is more than 1 MB/page.

I have checked document in Illustrator and here it is. Text is not stored as text, but as curves. All text. Looks terribly wrong.

![text](https://cloud.githubusercontent.com/assets/2384694/4856622/90afd8f0-60be-11e4-8c78-b97c0c90ed3c.png)

For my cases this is a surely not acceptable. Maybe there is an option to include text as text, not as curves?

**Comment by mauvm** [comment]
Additionally text is not selectable and links are not clickable. https://github.com/ariya/phantomjs/issues/10373

**Comment by adamwong246** [comment]
+1 Same here. Enormous file and unselectable text. 
I'm installing phantomjs with brew, which seems to indicate a patch would fix this problem. No success yet however

**Comment by jhawkinsatgood** [comment]
For what it's worth, PhantomJS on Windows produces texty PDFs instead of just images.

**Comment by jomag** [comment]
Same problem. 15k markdown results in 4.8 MB PDF. The problem seems to be that the fonts are converted to path. This is a showstopper for me. Any progress on this?

**Comment by anko** [comment]
This is an OS-X-only PhantomJS issue.

This PR ariya/phantomjs#13243 looks like a fix. People on OS X, could you test and recommend upstream to merge it?

**Comment by adamwong246** [comment]
I'm not optimistic about https://github.com/ariya/phantomjs/pull/13243. I ran some tests with https://github.com/astefanutti/phantomjs/tree/QTBUG-10094 and was unable to achieve better results :-(

**Comment by astefanutti** [comment]
@adamwong246 would you be able to share a reproducible test case so that I can give a run and confirm or not whether ariya/phantomjs#13243 fixes that issue as well.

**Comment by webdif** [comment]
I just tested markdown-pdf with providing `phantomPath` to v2 binary of phantomJS, with no luck.
The size of the file was divided by 2 and the font is different, but I am still having curves, not texts.

**Comment by alanshaw** [comment]
Please give v7.0.0 of markdown-pdf a go - phantomjs finally fixed this issue

**Comment by adamwong246** [comment]
+1 Thanks a lot!
