### ISSUE TITLE
header and footer didn't work

### ISSUE THREAD

**Issue by qiluo** [alanshaw/markdown-pdf#39]
I followed the guide to print custom header and footer, here's what I did

1. create a running.js with content

```
exports.header = {
    height: "1cm",
    contents: function(pageNum, numPages) {
        return "<h1>HEADER <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>"
    }
 };

exports.footer = {
    height: "1cm",
    contents: function(pageNum, numPages) {
        if (pageNum == numPages) {
            return "";
        }
        return "<h1>FOOTER <span style='float:right'>" + pageNum + " / " + numPages + "</span></h1>";
    }
}
```

2. generate pdf from cli

```
markdown-pdf xxx.md -f A4 -h running.js
```

I waited for ten minutes but it generated nothing, on the other hand, it successfully generated a pdf without runnings-path option

what did I do wrong?

**Comment by jhawkinsatgood** [comment]
I found that it only works with an absolute path for the runnings file. See also the issue here:
https://github.com/alanshaw/markdown-pdf/issues/35

**Comment by alanshaw** [comment]
Thanks @jhawkinsatgood I'll aim to get that fixed asap. The culprit is https://github.com/alanshaw/markdown-pdf/blob/master/lib/markdown-pdf.js#L17

**Comment by jhawkinsatgood** [comment]
I'm very nooby at nodejs but it seems to me that it would be better to use path.join instead of string concatenation?

**Comment by qiluo** [comment]
not __dirname only, should also try process.cwd()

thanks @jhawkinsatgood , absolute path worked!

@alanshaw  please better add -v --verbose option to cli so that we can fast debugging
