### ISSUE TITLE
Concat multiple markdown files

### ISSUE THREAD

**Issue by rosshadden** [alanshaw/markdown-pdf#41]
Is there a way from the CLI to generate a PDF from more than one input markdown file?  If not, what do you recommend as a workaround, concatenating input files into a single file and running `markdown-pdf` on that?

Thanks

**Comment by alanshaw** [comment]
You should be able to do this now in markdown-pdf@5.1.0:
```
npm install -g markdown-pdf
markdown-pdf file0.md file1.md file2.md
```

**Comment by rosshadden** [comment]
Awesome, thanks for adding it!
