### ISSUE TITLE
How to include title or other document information in headers and footers

### ISSUE THREAD

**Issue by jhawkinsatgood** [alanshaw/markdown-pdf#42]
I'm raising this issue to see if anybody has any bright ideas.
It seems to me that there is be no easy way to include information like a document title or category in a footer or header, i.e. in the runnings.
It is not too hard to write a node Transform that reads the input .md and fishes out, say, the first level one heading. That could be assumed to be the title, and then retained for use in the runnings. However, it looks like the runnings JS has to be a file, it can't be a stream or even just passed by setting a JS variable. (Actually, maybe it would be possible for code in the runnings JS to read a value set by a different module?)

There doesn't seem to be a node module for creating temporary files in a platform independent way, which makes this worse, I think.

**Comment by jhawkinsatgood** [comment]
Well, I ended up writing a Perl script to:
-   Parse the input Markdown and create a JSON string with some document information in it.
-   Create temporary JS files that include some code to set the JSON string into an object as a prefix.
-   Make a system call to kick off the nodejs run and generate the PDFs.

**Comment by alanshaw** [comment]
I guess you could have used the [preProcessMd](https://github.com/alanshaw/markdown-pdf#optionspreprocessmd) option to create a temporary `runnings.js` file.

**Comment by jhawkinsatgood** [comment]
It didn't seem easy to create a temporary file in the platform OS's default location in the nodejs API. It is very easy in Perl, in the File::Temp module (http://perldoc.perl.org/File/Temp.html).

**Comment by alanshaw** [comment]
markdown-pdf uses the tmp module - https://www.npmjs.com/package/tmp but you could also make use of the built in `os.tmpdir` function - https://nodejs.org/api/os.html#os_os_tmpdir

**Comment by jhawkinsatgood** [comment]
Neat.
