### ISSUE TITLE
Images in the runnings are not being shown if not present in the document

### ISSUE THREAD

**Issue by bodrovis** [alanshaw/markdown-pdf#43]
I have noticed a strange thing: an image is not being shown in the runnings if it is not present in the body of the document. For example:

_runnings.js_

``` js
exports.header = {
 height: "390px",
 contents: function(pageNum, numPages) {
  return "<img src='F:/1/head-2.png'>"
 }
}

exports.footer = {
 height: "204px",
 contents: function(pageNum, numPages) {
  return "<img src='F:/1/foot-2.png'>"
 }
}
```

_doc.md_

``` md
![](F:/1/head-2.png)
```

The `head-2.png` image is displayed in the header, but the `foot-2.png` is not. If I add

_doc.md_

``` md
![](F:/1/head-2.png)
![](F:/1/foot-2.png)
```

both images are shown in the header and the footer. If I remove them, none are shown at all.

Am I doing something wrong?

**Comment by neooblaster** [comment]
Hi,
Your workaround can be explain with this issue from Phantom.js : 
https://github.com/ariya/phantomjs/issues/14178

Content allow Phantom to cache image.
Without it, header and Footer can not load image.

For me, that do not works.

**Comment by bodrovis** [comment]
Perhaps. I have not used markdown-pdf for quite some time already so maybe this issue is resolved.

**Comment by neooblaster** [comment]
Threads are always open from Phantomjs.
For me that does not works.
Maybe it's a very hard issue ;)

**Comment by bodrovis** [comment]
AFAIK, PhantomJS is not maintained anymore.

**Comment by neooblaster** [comment]
Ah that why !

**Comment by bodrovis** [comment]
As a bottomline, this issue seems to be related to the one posted above. As long as PhantomJS is not maintained anymore, that problem is unlikely to resolved. Therefore, I'm closing the issue.
