### ISSUE TITLE
Compatibility with github-markdown-css

### ISSUE THREAD

**Issue by brunowego** [alanshaw/markdown-pdf#52]
This project is really cool and I think a use with [github-markdown-css](https://github.com/sindresorhus/github-markdown-css) will be nicer.

**Comment by rabidaudio** [comment]
+1

May send a PR for this in the future

**Comment by sankethkatta** [comment]
+ 1

**Comment by qiutiaoming** [comment]
+1

**Comment by belyan** [comment]
+1

**Comment by ckreon** [comment]
Why isn't it compatible at the moment? Shouldn't you be able to point to the github-markdown css file with the

**Comment by ckreon** [comment]
I made a pull-request to address this - #91.

**Comment by brunowego** [comment]
Thanks @ckreon

**Comment by timarcosdias** [comment]
@ckreon I got your PR modifications and added the options object like in your README.md but it's still not being styled.

**Comment by ckreon** [comment]
@timarcosdias Can you show your config/script?

**Comment by timarcosdias** [comment]
@ckreon I added `pdf_ghm.css` to my `markdown-pdf` installation and my code looks like:

```
var options = {
  cssPath: 'C:/Users/Marcos/node_modules/markdown-pdf/css/pdf_ghm.css'
}

markdownpdf(options)
  .concat
  .from(mdDocs)
  .to(bookPath, function () {
    console.log("Created", bookPath)
  })
```

I get no different result without the `options` object.

**Comment by ckreon** [comment]
@timarcosdias Try grabbing just the CSS file from my PR - and save it to your local drive. Use the current official release of MarkdownPDF and just use the options to point to that custom CSS file.

Here's part of my script file for you to reference, my CSS file is named `_pdf_style.css`:

    var ops = {
      cssPath: '_assets/css/_pdf_style.css',
      remarkable: {
        xhtmlOut: true,
        linkify: true
      }
    }

I use a relative path, as you can see, as opposed to an absolute path like you defined, though that shouldn't cause any issues as long as you are running it from your local environment.

**Comment by timarcosdias** [comment]
@ckreon It still doesn't work. I worked it out with Gitbook + Calibre. I recommend it! Anyway, thank you for the support.
