### ISSUE TITLE
Need help to use highlight.js with markdown-pdf

### ISSUE THREAD

**Issue by jeud** [alanshaw/markdown-pdf#53]
I have some coding in my markdown

    var hello = 'Hello World';
    function sayHello() {
        console.log(hello);
    }

How can I attach coding below into the HTML before transforming to PDF ?

    <script src="js/highlight.pack.js"></script>

    <script>
        hljs.configure({
  	    languages: ['javascript']
	})

	hljs.initHighlightingOnLoad();
    </script>

Or how can I use my own index.html as template instead of the default *[module path]/markdown-pdf/html5bp/index.html* ?
Please guide
Thanks

**Comment by anko** [comment]
Markdown documents [can have inline HTML](http://daringfireball.net/projects/markdown/syntax#html). Just add the `<script>...</script>` as-is. However, it's off by default in [remarkable](https://github.com/jonschlinkert/remarkable); you'll have to add the flag `--remarkable-options '{"html":true}'` to `markdown-pdf` to enable it.

**Comment by alanshaw** [comment]
@jeud please re-open if you're still having issues :)
