### ISSUE TITLE
Spaces in path to image file

### ISSUE THREAD

**Issue by jhawkinsatgood** [alanshaw/markdown-pdf#54]
Looks like you cannot have spaces in the path to an image file?

    ![](/Users/jhawkins/Documents/ok.png)

    ![](/Users/jhawkins/Documents/not ok.png)

**Comment by anko** [comment]
[Spaces are illegal in URLs](https://url.spec.whatwg.org/#url-writing).
[Encode it to `%20`](http://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space)?

**Comment by alanshaw** [comment]
@jhawkinsatgood did this work for you?

**Comment by jhawkinsatgood** [comment]
I adopted a practice of not having spaces in image file names.

I should also point out that, for a number of reasons, I decided to move "down the food chain" and switch to using MultiMarkdown and PhantomJS directly from a Perl script.

**Comment by pseudosavant** [comment]
My solution to this issue was to load all the markdown files myself into a large string and prepend `file:///` and `process.cwd()`. I also convert spaces to %20 and convert backslashes (from Windows) to forward slashes.

Example:

    const absolutePath = 'file:///' + process.cwd().replace(/ /g, '%20').replace(/\\/g, '/') + '/';
    const find = /img src="/g;
    const replace = 'img src="' + absolutePath;
    const mdStr = mdSourceStr.replace(find, replace);

**Comment by bobf** [comment]
@anko After a few hours of pulling my hair out, your comment fixed my problem. Seems obvious now. Thank you !

**Comment by sba923** [comment]
Yes `%20`'s the trick. Oughta be documented somewhere.

**Comment by gotfredsen** [comment]
> @jhawkinsatgood did this work for you?

Yes, that works!
