### ISSUE TITLE
<img> tags broken

### ISSUE THREAD

**Issue by lencioni** [alanshaw/markdown-pdf#56]
I'm using the grunt task and am just trying to upgrade to 3.0.0 and noticed that all of my `<img>` tags are no longer working. Instead of showing the image, it just ends up rendering the markup. I think that markup is allowed in markdown, so this seems like a bug to me.

**Comment by alanshaw** [comment]
I think you need to pass the html option to remarkable for this to work:
See https://www.npmjs.com/package/remarkable#options and https://github.com/alanshaw/markdown-pdf#optionsremarkable

Please re-open if your html is still not being rendered.
