### ISSUE TITLE
CLI Option: Stop After Rendering Intermediate HTML

### ISSUE THREAD

**Issue by ahemmeter** [alanshaw/markdown-pdf#58]
Most code compilers have a flag that tells the compiler to stop after a certain point and show the intermediate file. For example, when compiling C-code with gcc, you can tell the compiler to stop after the preprocessor has run and show the resulting C code, or to stop after it has been translated to assembly and show the resulting assembly code.  
  
When using this from the command line, it would be nice to be able to tell it to preserve the HTML file, so that I can use that for writing my CSS.

**Comment by anko** [comment]
Does [the close](https://github.com/alanshaw/markdown-pdf/issues/58#event-355402181) mean you figured it out?

Either way, for the benefit of anyone coming along later: markdown-pdf [uses](https://github.com/alanshaw/markdown-pdf/blob/master/package.json#L34) the [`remarkable` library](https://www.npmjs.com/package/remarkable) to convert from Markdown to HTML, which you can also use separately if you want to see just HTML output.

**Comment by woodrowbarlow** [comment]
apologies. i posted that issue, not realizing i was logged into my friend's account, so i closed it with the intention of re-opening it under my account, but i ended up just building with remarkable manually anyway (as you suggested).  
  
sorry for cluttering your repo.
