### ISSUE TITLE
if markdown-pdf support # 

### ISSUE THREAD

**Issue by binhe22** [alanshaw/markdown-pdf#62]
if markdown-pdf support # ?
How can I define the word size of the head?

Thanks

**Comment by anko** [comment]
If you mean `#` as in [atx-style headers](http://daringfireball.net/projects/markdown/syntax#header), then yes it does. They are rendered as `<h1>`, `<h2>`, … elements in the HTML, before being converted to PDF.

To change their size, pass a custom CSS file as the [`cssPath` option](https://github.com/alanshaw/markdown-pdf#optionscsspath), containing something like—

```css
h1 { font-size : 15pt }
```

**Comment by alanshaw** [comment]
Assuming this is resolved...

**Comment by DevNaga** [comment]
if any css added (without any font option), the default font size of generated pdf goes to 14pt, 

also needs,

```css
body { font-size: 9pt }
````
to please better to the eyes..
