### ISSUE TITLE
remarkable Syntax Extensions

### ISSUE THREAD

**Issue by miso440** [alanshaw/markdown-pdf#67]
My application of markdown-pdf would benefit greatly from some of the [optional syntax](https://github.com/jonschlinkert/remarkable#syntax-extensions) available from remarkable, specifically super/sub-script and footnotes.

I see no way to activate these from the documentation so I edited the `flush()` function in [markdown-pdf/index.js](https://github.com/alanshaw/markdown-pdf/blob/master/index.js) to include the following code:

```js
mdParser.block.ruler.enable([
	'footnote'
])
	  
mdParser.inline.ruler.enable([
	'sup',
	'sub'
])
```

This solution works, as expected, but if there exists a cleaner way to enable these features from a script which includes markdown-pdf I'd like to learn of it.

**Comment by jasonb-vbt** [comment]
+1 I don't need those features myself in my current project, but they seem like good ones to have.

**Comment by alanshaw** [comment]
Let me know if https://github.com/alanshaw/markdown-pdf#optionsremarkablesyntax isn't working for you

**Comment by XAMelleOH** [comment]
@alanshaw 

How can I call `markdown-pdf` with that option:
```
let md = new Remarkable().use(function(remarkable) {
  remarkable.renderer.rules.heading_open = function(tokens, idx) {
    return '<h' + tokens[idx].hLevel + ' id=' + toc.slugify(tokens[idx + 1].content) + '>';
  };
});
```
