### ISSUE TITLE
Error when using CLI mode

### ISSUE THREAD

**Issue by ManuCart** [alanshaw/markdown-pdf#70]
````
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Command failed: /usr/local/lib/node_modules/markdown-pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs: 1: /usr/local/lib/node_modules/markdown-pdf/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: word unexpected (expecting ")")

    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Socket.<anonymous> (child_process.js:968:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
````

**Comment by anko** [comment]
What command exactly did you run?

**Comment by ManuCart** [comment]
I just run this
```markdown-pdf test.md```

**Comment by anko** [comment]
I tried to reproduce it.

 - OS: Linux
 - `node -v`: v5.1.0
 - `markdown-pdf --version`: 6.0.0

```
mkdir test
cd test
npm i markdown-pdf
echo "#hi" > test.md
./node_modules/.bin/markdown-pdf test.md
```

Got a `test.pdf` with the expected contents. No errors.

Could you post exact steps?

**Comment by ManuCart** [comment]
node -v ````v0.10.29```` (strange version)
markdown-pdf --version ````5.3.0````

How to update this ?

**Comment by ManuCart** [comment]
I found this other error
````PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
````
Help me!

**Comment by anko** [comment]
>     PhantomJS not found on PATH
>     Unexpected platform or architecture: linux/arm
>     It seems there is no binary available for your platform/architecture
>     Try to install PhantomJS globally

I think I see what's happening.

`linux/arm` suggests you're running something with an [ARM processor][1], perhaps a [Raspberry Pi][2]?  The [npm phantomjs package][3] tried to download the correct version of the [phantomjs headless browser][4] for your platform, but it doesn't seem to have one compiled for ARM.

Try downloading [this phantomjs binary built for the Raspberry Pi][5] (it's under `bin/`) and point `markdown-pdf` to it using the `--phantom-path` command line flag.

[1]: https://en.wikipedia.org/wiki/ARM_architecture
[2]: https://www.raspberrypi.org/
[3]: https://www.npmjs.com/package/phantomjs
[4]: http://phantomjs.org/
[5]: https://github.com/piksel/phantomjs-raspberrypi

**Comment by alanshaw** [comment]
@ManuCart did you resolve your problem?

**Comment by ManuCart** [comment]
No, but never mind I use an other apps.
