### ISSUE TITLE
Expose remarkable presets

### ISSUE THREAD

**Issue by tgeens** [alanshaw/markdown-pdf#71]
Using the default constructor, the 'default' remarkable presets get loaded at https://github.com/jonschlinkert/remarkable/blob/dev/lib/index.js#L53

I would like to be able to pass one of the available presets to remarkable.

Would the *options*-object that is passed to *markdownpdf(options)* a good place to do just that ?

**Comment by alanshaw** [comment]
Is this what you're looking for?
https://github.com/alanshaw/markdown-pdf#optionsremarkable

**Comment by tgeens** [comment]
Not exactly.

What I actually wanted it to enable to [sup- and sub-](http://johnmacfarlane.net/pandoc/README.html#superscripts-and-subscripts)script syntax extensions. The are supported by remarkable, but disabled by default.

I can't find a way in the documentation or code to enable them through the options-object. The documented way to enable them is this:

```js
var md = new Remarkable();
md.block.ruler.enable([
  'sub',
  'sup'
]);
```

That's not very pragmatic in my opinion.

Remarkable has another feature, called *presets*. It's a string that refers to a set of rules/config/syntax-extensions. There are 3 presets [https://github.com/jonschlinkert/remarkable/blob/dev/lib/index.js#L14](predefined): 'default', 'commonmark' and 'full'.

If I can pass along a preset 'full', I don't need a way to access those rules, etc ...

Remarkable supports the presets, by making it an optional parameter in the constructor, by checking the type of the first argument (and re-assigning parameters if only options is provided as 1st arg):

```js
function Remarkable(preset, options) {
  if (typeof preset !== 'string') {
    options = preset;
    preset = 'default';
  }
  ....
```
Source: https://github.com/jonschlinkert/remarkable/blob/dev/lib/index.js#L53

If markdown-pdf wants to supports these presets, there are 2 straight forward options:

* use a similar construction in the function ```markdownpdf(opts)``` as remarkable does
* add a special case in the options object for opts.remarkable.preset (like ```opts.remarkable.plugins```)
