### ISSUE TITLE
Creating a colored pdf without page margins

### ISSUE THREAD

**Issue by jdwestermann** [alanshaw/markdown-pdf#74]
Is there any way to create a fully colored pdf (e.g. black background, white font-color) without any page margins? I found a similar problem in #7 , however I cannot get myself to do the trick. I overwrote any related H5BP media styles in my custom css as can be seen below:

<pre><code>@media print {
	@page {
		background:#000 !important;
		margin:0 !important;
		-webkit-print-color-adjust: exact !important;
	}
}

body {
	font-family: "Avenir Next", Helvetica, Arial, sans-serif;
	padding:1em;
	margin:auto;
	max-width:42em;
	background-color:#000000 !important;
	-webkit-print-color-adjust: exact;
	color:#fefefe;
}</code></pre>

* OS: Mac OS
* markdown-pdf version: 6.0.0

**Comment by alanshaw** [comment]
I was able to do this using markdown-pdf@7.0.0 the following args on the command line:

```
markdown-pdf doc.md -s pdf.css -b 0cm
```

With CSS file:

```css
body {
  background-color: black;
}
```
