### ISSUE TITLE
Keep temporary generated HTML

### ISSUE THREAD

**Issue by dotmagic** [alanshaw/markdown-pdf#75]
I would like to have a option to save the generated HTML because it helps me to understand how to style it better. I guess actually its only possible with preProcessHtml?

**Comment by alanshaw** [comment]
It uses [remarkable](https://www.npmjs.com/package/remarkable) and the output is put in the HTML5BP [index.html](https://github.com/alanshaw/markdown-pdf/blob/master/html5bp/index.html).

There's a few different ways you could do this:

1. Use remarkable directly to see the html that gets generated
2. Simply `console.log` in `preProcessHtml`
3. Use `fs.createWriteStream` and write to that whenever `preProcessHtml` gets a chunk

**Comment by dotmagic** [comment]
Hi Alan,

i did use `preProcessHtml` but it returns the HTML from remarkable before it's joined with HTML5BP.

My goal is to have the full HTML *with* my custom Stylesheets + Syntax Highlight, so i can open and it in my Webbrowser and debug with Web Developer Tools. Actually its lots of trial & error to create a custom Stylesheet because i can only see the rendered PDF. I try to create now a seperate remarkable Task to archive my goal, but i still think a option to save HTML for debugging purpose or generating other formats (like epub) would be useful.

**Comment by WillyBrownHair** [comment]
I have the same request !

**Comment by dotmagic** [comment]
@WillyBrownHair You can try my setup but you may adjust the code to your needs: https://github.com/dotmagic/markdown2pdf

I did also add SCSS and nunjucks Template support.
