### ISSUE TITLE
old node engine in package.json

### ISSUE THREAD

**Issue by codekirei** [alanshaw/markdown-pdf#76]
Currently, this module requests a fairly old version of node in `package.json`:

```js
  "engines": {
    "node": "~0.10.0"
  },
```

This triggers a warning on install for significantly newer versions of node (as it should):

```bash
WARN engine markdown-pdf@6.0.0: wanted: {"node":"~0.10.0"} (current:{"node":"5.4.0","npm":"3.5.3"})
```

`markdown-pdf` seems to function just fine for me on `5.4.0`, and all tests pass.

Just wondering if there is any specific reason for using `~0.10.0` besides that being the only version of Node currently tested by Travis for this module? If it's just Travis, we could [add some newer versions](https://docs.travis-ci.com/user/languages/javascript-with-nodejs) to `.travis.yml` and bump up the value in `package.json` to something like `>=0.10.0 <4.2`. I know that this would still throw the warning for me because my version of Node is outside that range, but `4.1` is the latest version currently supported by Travis, so not much we can do about that for now :innocent:

Would be happy to submit a quick little PR with `package.json` and `.travis.yml` updated if you'd like, just say the word!

**Comment by anko** [comment]
Not waiting for the word. :smiling_imp:

**Comment by codekirei** [comment]
Hey awesome! Thanks for the quick turnaround :+1:
