### ISSUE TITLE
Stopping by to say thank you

### ISSUE THREAD

**Issue by jorinvo** [alanshaw/markdown-pdf#79]
I just would like to say thank you for creating this module!
Works perfect for me! I wrote a little summary about my use case: https://jorin.me/homework-in-markdown/

Feel free to close this issue. 
And keep up the good work!

Greetings Jorin

**Comment by anko** [comment]
Coursework was my first use-case too! I couldn't be bothered to learn [LaTeX](https://en.wikipedia.org/wiki/LaTeX).

In case it's helpful in the future, I found [`make`](https://en.wikipedia.org/wiki/Makefile) to be great for more complex documents. I needed a bunch of diagrams, so I generated them in JavaScript using [D3](http://d3js.org/), which was slow, but `make` figured out what files changed and only recompiled those.

**Comment by alanshaw** [comment]
You're very welcome. Thanks for taking the time to say.
