### ISSUE TITLE
HTML Conversion

### ISSUE THREAD

**Issue by Pacerier** [alanshaw/markdown-pdf#85]
What tool/library do you use for converting markdown to HTML?

Is this the exact same output as Github's HTML output?

**Comment by anko** [comment]
Markdown-pdf uses [remarkable](https://github.com/jonschlinkert/remarkable).

It's _not guaranteed_ to give the same output as Github's [markup](https://github.com/github/markup) library, which is for the Ruby programming language.

If you'd like to have output as similar as possible to Github README.md files, I'd recommend using [sindresorhus/github-markdown-css](https://github.com/sindresorhus/github-markdown-css) as your custom CSS.
