### ISSUE TITLE
CSS howto?

### ISSUE THREAD

**Issue by dncohen** [alanshaw/markdown-pdf#87]
This is a nice tool.  Thanks for sharing it!
I'm getting nice pdf output.  However I want to make minor tweaks.  Specifically right now I'm trying to make the font in a code block smaller so that I can fit more on a page.
It's not clear to me what rules to add to my custom .css.  I wish there were some way to see the HTML that preceeds the PDF output.
Or if anyone has custom css examples to share...

**Comment by anko** [comment]
Markdown-pdf currently does the conversion into HTML internally: it's not possible to see it unless you open it up and change the code yourself. (If you want to, the temporary HTML file is created [here](https://github.com/alanshaw/markdown-pdf/blob/master/index.js#L88-L91).)

The rules for converting Markdown→HTML are very straightforward though. [This tool](http://spec.commonmark.org/dingus/?text=%23%23%20Try%20CommonMark%0A%0AYou%20can%20try%20CommonMark%20here.%20%20This%20dingus%20is%20powered%20by%0A%5Bcommonmark.js%5D(https%3A%2F%2Fgithub.com%2Fjgm%2Fcommonmark.js)%2C%20the%0AJavaScript%20reference%20implementation.%0A%0A%20%20%20%20hello()) is great for understanding how it works.

For example, code blocks become `<pre>` tags, so a custom CSS like—

```css
pre {
  font-size: 70%;
}
```

—should reduce their size.

Does that help?

**Comment by jhawkinsatgood** [comment]
Hi, I haven't tried it but it seems to me that you could use the options.preProcessHtml parameter to dump out the HTML to a file. That way, you wouldn't have to change the code. Cheers, Jim

**Comment by dncohen** [comment]
This was very helpful thanks.  Especially the tool linked above which shows the html.
