### ISSUE TITLE
How to set options.phantomPath ?

### ISSUE THREAD

**Issue by taiji1985** [alanshaw/markdown-pdf#88]
When I use Atom , I want to use this plugin to convert md to pdf. It show the follow message:

markdown-pdf: AssertionError: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'

I had install phantomJS , How can i  set "options.phantomPath' .  How to set ???
I have try to set os env , but it not works.
Thanks !

**Comment by alanshaw** [comment]
This isn't the repo for an atom plugin...

**Comment by taiji1985** [comment]
Thanks .
