### ISSUE TITLE
Ignore Jekyll front-matter text during PDF renderings

### ISSUE THREAD

**Issue by ckreon** [alanshaw/markdown-pdf#89]
When rendering an MD file from a Jekyll project, it renders the front-matter text as well (text which defines various properties of the file for Jekyll to process).

Is there a way to not render that front-matter text? It is delimited by three dashes, like so:
```
---
front-matter text
---
Normal file content begins.
```

**Comment by anko** [comment]
Remarkable (the library we use to parse markdown) doesn't support Jekyll front matter. Their reasoning is explained here: https://github.com/jonschlinkert/remarkable/issues/16. Front matter is a Jekyll feature, not a Markdown feature. In Markdown, it's ambiguous with one syntax for a [horizontal rule](https://daringfireball.net/projects/markdown/syntax#hr).

You could—

 - use [the json-front-matter module](https://github.com/jsantell/node-json-front-matter) and pass just `.body` to markdown-pdf, or
 - strip it yourself with a regex

   ```js
   // Strip everything between the first two sets of '---'
   var body = fileContents.replace(/^---\n.*\n---\n/, '')
   ```

**Comment by ckreon** [comment]
Thank you for the explanation, and I really appreciate the solutions offered.
